apiVersion: v1
kind: Service
metadata:
  name: rabbit-svc
spec:
  type: ClusterIP
  selector:
    app: rabbit-pod
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: amqp
      protocol: TCP
      port: 5672
    - name: prom
      protocol: TCP
      port: 9419

