apiVersion: v1
kind: Service
metadata:
  name: mt3chained-step1-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: mt3chained  
spec:
  selector:
    tier: mt3chained-step1-pod
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 80
      name: http
  type: ClusterIP
