apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
        color: lime
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule