# Mounting the secret only will not work:
#  https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
#
# "The secrets will sync only after you start a pod to mount them. 
#  To rely solely on syncing with the Kubernetes secrets feature doesn't work. 
#  When all the pods that consume the secret are deleted, the Kubernetes secret is also deleted"
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret
spec:
  provider: azure           
  secretObjects:                             # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: secret-db-connection   # data field in secret to populate
      objectName: dbConnection    # name of the object from the key vault
    secretName: local-secret-1      # name of the Kubernetes secret object to create
    type: Opaque                   
  parameters:
    usePodIdentity: "false"               # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: kiz-kube-kv
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 4a0d4211-310e-4fc2-b7fc-3891c53658c3
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    objects: |
      array:
        - |
          objectName: dbConnection
          objectType: secret             # object types: secret, key, or cert
          objectVersion: "" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-kv-secret
  labels:
    scope: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:      
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            protocol: TCP
        env:
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: local-secret-1
              key: secret-db-connection
        # volumeMounts:
        # - name: secrets-kiz-kube-kv
        #   mountPath: /mnt/kv-secrets"
        #   readOnly: true              
      nodeSelector:
        kubernetes.io/os: linux  
      volumes:
      - name: secrets-kiz-kube-kv
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kv-secret
                     