
# Reference: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-volume-and-secret
spec:
  provider: azure 
  secretObjects:           # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: DB_CONNECTION          # data field in secret to populate
      objectName: dbConnection    # name of the object from the kv
    - key: SEISMIC_VALUE          # data field in secret to populate
      objectName: Seismic         # name of the object from the kv      
    secretName: local-secret-2    # name of the Kubernetes secret object to create
    type: Opaque           
  parameters:
    usePodIdentity: "false"       # Set to true for using aad-pod-identity to access your key vault
    keyvaultName: kiz-kube-kv
    useVMManagedIdentity: "true"    
    userAssignedIdentityID: 4a0d4211-310e-4fc2-b7fc-3891c53658c3
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    objects: |
      array:
        - |
          objectName: dbConnection
          objectType: secret             # object types: secret, key, or cert
          objectVersion: "" 
        - |    
          objectName: Seismic
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-kv-volume-and-secret
  labels:
    scope: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:      
      labels:
        app: myapp
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            protocol: TCP
        envFrom:
          - secretRef:
              name: local-secret-2
        # env:    
        # - name: DB_CONNECTION
        #   valueFrom:
        #     secretKeyRef:
        #       name: local-secret-2
        #       key: secret-db-connection 
        # - name: SEISMIC_VALUE
        #   valueFrom:
        #     secretKeyRef:
        #       name: local-secret-2
        #       key:  seismic-value
        volumeMounts:
        - name: secrets-kube-kv
          mountPath: /mnt/kv-secrets
          readOnly: true
      volumes:
        - name: secrets-kube-kv
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-volume-and-secret