apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-kv-secret
  labels:
    scope: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-secret
  template:
    metadata:      
      labels:
        app: myapp-secret
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            protocol: TCP
        env:
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: local-secret
              key: secret-db-connection
      nodeSelector:
        kubernetes.io/os: linux  
      volumes:
      - name: secrets-kiz-kube-kv
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kv
                     