apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-1-dep
spec:
  replicas: 6
  minReadySeconds: 15
  selector:
    matchLabels:
      app: workload-1
  template:
    metadata:
      labels:
        app: workload-1
        color: maroon
    spec:
      containers:
        - name: workload
          image: nginx:1.17
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
