apiVersion: v1
kind: Service
metadata:
  name: production-svc
  labels:
    color: blue
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 80
  selector:
    target: blue-dep
  type: LoadBalancer