apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    kind: api
    target: dev
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
  - image: mysql:5.7
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP      
    env: 
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "true"
  nodeSelector:
    kubernetes.io/os: linux
