apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt3chained-step1-dep
  namespace: {{ .Values.namespace }}
  labels:
    app: mt3chained
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: mt3chained-step1-pod
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mt3chained-cm.yaml") . | sha256sum }}
      labels:
        tier: mt3chained-step1-pod
        color: tomato
    spec:
      serviceAccountName: mt3chained-step1-sa
      containers:
      - name: mt3chained-step1
        image: {{ .Values.repo }}/mt3chained-step1:{{ .Values.tags.mt3chainedstep1 }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mt3chained-config        
        env:
        - name: NextStepEndpoint
          value: http://mt3chained-step2-svc:5020 
        - name: CalcStepVariable
          value: "2"
        imagePullPolicy: Always