apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-liveness-probe
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        # The kubelet uses liveness probes to know when to restart a container.
        # Start only AFTER the startupProbe has completed successfully 
        # Pings the path every 5 seconds.  
        # Restarts the containers if the ping ever fails (no retries)
        livenessProbe:
          httpGet:
            path: /healthy
            port: 80
          failureThreshold: 1
          periodSeconds: 5
          initialDelaySeconds: 15 