apiVersion: v1
kind: LimitRange
metadata:
  name: chained-limit-range
  namespace: {{ .Values.namespace }}
  labels:
    app: mt3chained
spec:
  limits:
    # Default limit if not specified
    - default:
        cpu: 100m
        memory: 256Mi
      # Default request if not specified
      defaultRequest:
        cpu: 50m
        memory: 200Mi
      # Max limit if specified
      max:
        cpu: 1
        memory: 1Gi
      # Min request if specified
      min:
        cpu: 50m
        memory: 64Mi
      type: Container
