name: Math Trick 3 - Chained-Web-CI

on:
  push:
    branches:
      - main

env:
  APP_NAME: <appName>
  LOGIN_SERVER: <acrServerName>

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      # Connect to Azure Container Registry (ACR)
      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_PASSWORD }}

      # Container build and push to a Azure Container Registry (ACR)
      - name: Build, tag, and push image to ACR
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: |
            ${{ env.LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.run_number }}
          ## <latestTag> ##
