apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-2
  labels:
    scope: demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
        color: red
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80               
      nodeSelector:
        kubernetes.io/os: linux       
