apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-3
  labels:
    scope: demo  
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:        
        app: nginx-3        
        color: blue
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80          
      nodeSelector:
        kubernetes.io/os: linux         