apiVersion: v1
kind: Service
metadata:
  name: mt3gateway-step3-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: mt3gateway
spec:
  selector:
    tier: mt3gateway-step3-pod
  ports:
    - protocol: TCP
      port: 5030
      targetPort: 80
      name: http
  type: ClusterIP
