apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-1-dep
spec:
  replicas: 3
  selector:
    matchLabels:
       target: canary-pod       
  template:
    metadata:
      name: canary-1
      labels:
        target: canary-pod
        version: "1.0"
        color: yellow
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: servicedemo
        image: scubakiz/servicedemo:1.0
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: Always
        env: 
        - name: IMAGE_COLOR
          value: yellow            
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP      
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name                    
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName 
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: servicedemo
              resource: requests.cpu
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: servicedemo
              resource: limits.cpu
        - name: POD_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: servicedemo
              resource: requests.memory
        - name: POD_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: servicedemo
              resource: limits.memory 
        volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo    

      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations

