apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload3-dep
  labels:
    app: demo
spec:
  replicas: 2
  minReadySeconds: 5      
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:
        app: nginx-3
        color: yellow
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
          - containerPort: 80
        resources: 
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi                              
      nodeSelector:
        kubernetes.io/os: linux
