apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload4-dep
  labels:
    app: demo
spec:
  replicas: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: nginx-4
  template:
    metadata:
      labels:
        app: nginx-4
        color: blue
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
          - containerPort: 80      
      nodeSelector:
        kubernetes.io/os: linux
