apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # certmanager.k8s.io/acme-challenge-type: dns01
    # certmanager.k8s.io/acme-dns01-provider: azuredns
    # certmanager.k8s.io/cluster-issuer: letsencrypt-production
    # ingress.kubernetes.io/force-ssl-redirect: "true"
    # ingress.kubernetes.io/ssl-redirect: "true"    
  name: colors-ingress-staging
spec:
  rules:
    # - host: 'fdpo.zipzapp.app'
    # - host: 'colors.zipzapp.tech'
    - http:
        paths:
        - path: /staging/blue(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service: 
              name: blue-svc
              port: 
                number: 8100
        - path: /staging/red(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service: 
              name: red-svc
              port: 
                number: 8100         
        - path: /staging/yellow(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service: 
              name: yellow-svc
              port: 
                number: 8100                   
  # tls:
  # - hosts:
  #   # - 'fdpo.zipzapp.app'
  #   - 'colors.zipzapp.tech'
  #   secretName: www-wildcard-tls