apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress-backend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # certmanager.k8s.io/acme-challenge-type: dns01
    # certmanager.k8s.io/acme-dns01-provider: azuredns
    # certmanager.k8s.io/cluster-issuer: letsencrypt
    # ingress.kubernetes.io/force-ssl-redirect: "true"
    # ingress.kubernetes.io/ssl-redirect: "true"    
spec:
  defaultBackend:
    service:
      # host: '*.zipzapp.app'
      name: default-svc
      port:
        number: 8100