apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: mt3chained-web-ing
  namespace: {{ .Values.namespace }}
spec:  
  rules:
    - http:
        paths:
          - path: /{{ .Values.namespace }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: mt3chained-web-svc
                port: 
                  name: http
