name: Deploy AKS Store Quickstart

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group rg-game-yeti --name cluster-lucky-goldfish

    - name: Deploy Application
      run: |
        kubectl apply -f aks-store-quickstart.yaml
        kubectl get pods
        kubectl get service store-front
      working-directory: Demos/TF