name: Deploy AKS Cluster

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: Demos/TF

    - name: Terraform Plan
      run: terraform plan -out main.tfplan
      working-directory: Demos/TF

    - name: Terraform Apply
      run: terraform apply -auto-approve main.tfplan
      working-directory: Demos/TF

    - name: Get Resource Group Name
      id: get_rg_name
      run: echo "::set-output name=resource_group_name::$(terraform output -raw resource_group_name)"

    - name: Get AKS Cluster Name
      id: get_aks_name
      run: echo "::set-output name=kubernetes_cluster_name::$(terraform output -raw kubernetes_cluster_name)"

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group ${{ steps.get_rg_name.outputs.resource_group_name }} --name ${{ steps.get_aks_name.outputs.kubernetes_cluster_name }}

    - name: Test Deployment
      run: |
        kubectl get nodes

    # - name: Deploy Application
    #   run: |
    #     kubectl apply -f aks-store-quickstart.yaml
    #     kubectl get pods
    #     kubectl get service store-front --watch