name: Deploy to K8S

on:
  workflow_dispatch:

jobs:
  deploy_manifests:
    runs-on: ubuntu-latest

    env:
      NS: itp

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group k8s-tech-brief-rg --name ktb-aks

    - name: Obtain Version
      run: |
        cd ${GITHUB_WORKSPACE}/Demos/planets
        dockerfile_path="./Dockerfile"
        line=$(grep -E 'LABEL VERSION=' "$dockerfile_path")
        regex='[0-9]+\.[0-9]+\.[0-9]+'
        [[ $line =~ $regex ]] && tag="${BASH_REMATCH[0]}"
        echo "Existing tag: $tag"
        echo "tag=$tag" >> $GITHUB_ENV

    - name: Deploy manifests
      run: |
        cd ${GITHUB_WORKSPACE}/Demos/planets/.k8s
        c=$(<./planets-web-app-dep.yaml)
        c=${c//"{{ .Values.tag }}"/$TAG}
        printf "%s\n" "$c" | kubectl apply -n $NS -f -
        kubectl apply -f ./planets-web-app-dep.yaml
      env:
        TAG: ${{ env.tag }}
        NS: ${{ env.NS }}