name: Deploy to K8S

on:
  workflow_dispatch:

jobs:
  deploy_manifests:
    runs-on: self-hosted # or use 'ubuntu-latest' if using GitHub-hosted runners

    env:
      NS: itp

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Obtain Version
      run: |
        cd ${GITHUB_WORKSPACE}/django/sample-app
        dockerfile_path="./Dockerfile"
        line=$(grep -E 'LABEL VERSION=' "$dockerfile_path")
        regex='[0-9]+\.[0-9]+\.[0-9]+'
        [[ $line =~ $regex ]] && tag="${BASH_REMATCH[0]}"
        echo "Existing tag: $tag"
        echo "tag=$tag" >> $GITHUB_ENV

    - name: Deploy manifests
      run: |
        cd ${GITHUB_WORKSPACE}/k8s/sample-django-app
        c=$(<./sample-django-app-dep.yaml)
        c=${c//"{{ .Values.tag }}"/$TAG}
        printf "%s\n" "$c" | kubectl apply -n $NS -f -
        kubectl apply -f ./sample-django-app-svc-cip.yaml -f ./sample-django-app-ing.yaml -n $NS
        kubectl apply -f sample-django-app-test-dep.yaml -n $NS
      env:
        TAG: ${{ env.tag }}
        NS: ${{ env.NS }}